### ISSUE TITLE
Weights Download Link is Dead

### ISSUE THREAD

**Issue by MikeTheSapien** [ValerioSpagnoli/EyeRoad#2]
As the title says, clicking the link from README.md results in a 404. 

This is the link: https://drive.google.com/drive/folders/1GNwxJwKyAZybAP71T0N0wo2yH6GAgzkP?usp=share_link

**Comment by ValerioSpagnoli** [comment]
I have fixed the link. Let me know if it works now

**Comment by MikeTheSapien** [comment]
Oh thank you! Now it works!

Not sure where to place this message but I appreciate your work. This is my first time tinkering with these kinds of projects. Been holding it off for so long since these are "fun" projects for me. Not work related.

Didn't see any **roadmap** in your docs. I want to contribute back and if  you need help making this more accessible or integrate-able to other projects, perhaps I can help you out. You give directions and I can do the legwork.
